language: node_js
node_js:
- lts/*

python:
- "3.6"

before_install:
  - npm install -g yarn --cache-min 999999999

install:
  yarn install


script:
  - python3 src/assets/parse_content.py
  - yarn run build


cache:
  directories:
  - node_modules

before_deploy:
- echo sfuml.haoxp.xyz > dist/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target-branch: gh-pages
  on:
    branch: master